### PR TITLE
examples: stm32f0: Add USB DFU example

### PR DESCRIPTION
**Pull request by adalessandro**
This commit adds an example to use the USB DFU (Device Firmware Upgrade)
mechanism on STM32F0 chips.

Note:
In order to boot the board using a (USB DFU) bootloader, the app interrupt vector
table has to be remapped.

Some STM32 chips have an interrupt vector offset register, so these
chips can use the app's interrupt vector in-flash by setting this register
properly.

As STM32F0 does not support this feature, the vector table is
copied at the beginning of RAM. Also, before jumping into the app,
bootloader maps the shadow memory area to RAM, so the vector table is used.

### CODE REVIEW

**Comment by kuldeepdhaka** [comment]
Code looks good since it uses the common code. (not personally tested)

**Comment by kuldeepdhaka** [comment]
Need to update string that contain flash information?
 https://github.com/insane-adding-machines/unicore-mx-examples/blob/master/examples/common/usb_dfu/usbdfu.c#L125
See: http://www.st.com/content/ccc/resource/technical/document/user_manual/01/c6/32/df/79/ad/48/32/CD00158241.pdf/files/CD00158241.pdf/jcr:content/translations/en.CD00158241.pdf `(UM0424STM32 USB-FS-Device development kit -> Chapter 10 Device firmware upgrade)`

**Comment by adalessandro** [comment]
Yep, you're right, the flash detail string has to be updated.

So, this string is defined in common code:
https://github.com/insane-adding-machines/unicore-mx-examples/blob/master/examples/common/usb_dfu/usbdfu.c#L122
`static const struct usb_string_descriptor string_st_flash_detail`

Which ultimately uses this string in the `struct usbd_info info` to initialize the usb device: https://github.com/insane-adding-machines/unicore-mx-examples/blob/master/examples/common/usb_dfu/usbdfu.c#L351
`usbd_dev = usbd_init(usbdfu_target_usb_driver(), NULL, &info);`

Should this string be target specific? I can submit a patch moving the declaration of this string to https://github.com/insane-adding-machines/unicore-mx-examples/blob/master/examples/common/usb_dfu/usbdfu-target.h and add the proper definitions in the different examples.

**Comment by adalessandro** [comment]
How does this look? https://github.com/adalessandro/unicore-mx-examples/commit/d8874c1d9751b9f4ec43652739c7fba2672f58b3

**Comment by kuldeepdhaka** [comment]
@adalessandro Now, all you need is:
1. adalessandro/unicore-mx-examples@d8874c1 in this PR.
2. F0 specific flash detail string descriptor.

**Comment by adalessandro** [comment]
@kuldeepdhaka, commits pushed.

**Comment by kuldeepdhaka** [comment]
```patch
--- a/examples/stm32/f0/stm32f042/usb_dfu/usbdfu-target.c
+++ b/examples/stm32/f0/stm32f042/usb_dfu/usbdfu-target.c
@@ -9,7 +9,7 @@
 #define APP_ADDRESS            0x08002000
 
 /* This string is used by ST Microelectronics' DfuSe utility. */
-static const struct usb_string_descriptor string_0 = {
+const struct usb_string_descriptor string_st_flash_detail = {
        .bLength = USB_DT_STRING_SIZE(46),
        .bDescriptorType = USB_DT_STRING,
        /* @Internal Flash   /0x08000000/8*001Ka,24*001Kg */
```

**Comment by adalessandro** [comment]
Ugh! (facepalm)... Fixed it. Sorry for the dirty push.

**Comment by kuldeepdhaka** [comment]
@adalessandro I can safely assume that the code worked for you (tested on hardware)?
Unfortunately i dont have a STM32F042 to check.

**Comment by adalessandro** [comment]
@kuldeepdhaka, yes, of course. I have a STM32F042 board here which I used to develop and test the patch. You can be sure this works fine ;-)

**Comment by kuldeepdhaka** [comment]
@adalessandro Thank you!

**Pull request merged**
